<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
//            CATEGORY ONE (1)
            ['name' => 'CBC & ESR (Government Price)', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 400],
            ['name' => 'Hemoglobin(HB%)', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 200],
            ['name' => 'TC', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 200],
            ['name' => 'DC', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 200],
            ['name' => 'ESR', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 200],
            ['name' => 'TC DC HB% ESR', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 400],
            ['name' => 'Circulating eosinophilS count', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 200],
            ['name' => 'Platelet Count', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 200],
            ['name' => 'Bleeding Time(BT)', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 200],
            ['name' => 'Clotting Time(CT)', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 200],
            ['name' => 'PBF (Peripheral blood film)', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 200],
            ['name' => 'PCV', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 200],
            ['name' => 'MCH', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 200],
            ['name' => 'MCHC', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 200],
            ['name' => 'Reticulocyte Count', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 200],
            ['name' => 'Microfilaria', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 200],
            ['name' => 'RBC', 'category_id' => 1, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 200],

//            CATEGORY ONE (2)

            ['name' => 'OGTT - 3 Sample', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 600],
            ['name' => 'RBS', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 200],
            ['name' => 'FBS', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 200],
            ['name' => '2 hours after 75 gm. Glucose', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 200],
            ['name' => '2 hours ABF', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 200],
            ['name' => 'Bilirubin - Total', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 400],
            ['name' => 'Bilirubin - Direct/Indirect', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 600],
            ['name' => 'SGPT (ALT)', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 400],
            ['name' => 'SGOT (AST)', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 400],
            ['name' => 'Alkaline Phosphatase', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 400],
            ['name' => 'Prothrombin Time', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 800],
            ['name' => 'APTT', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 800],
            ['name' => 'Lipid Profile', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 1200],
            ['name' => 'Cholesterol', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 400],
            ['name' => 'HDL', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 400],
            ['name' => 'LDL', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 400],
            ['name' => 'Triglyceride', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 400],
            ['name' => 'Urea', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 400],
            ['name' => 'LFT(Government Price)', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 1000],
            ['name' => 'Creatinine(Government Price)', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 400],
            ['name' => 'd.Dimer(Government Price)', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 1500],
            ['name' => 'Total Protein', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 800],
            ['name' => 'Albumin', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 600],
            ['name' => 'Globulin', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 350],
            ['name' => 'A/G Ratio', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 700],
            ['name' => 'S.Uric-Acid', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 500],
            ['name' => 'S.Calcium', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 500],
            ['name' => 'S.Alpha Amylase', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 1000],
            ['name' => 'Acid Phosphatase', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 1000],
            ['name' => 'CPK', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 1000],
            ['name' => 'CKMD', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 1000],
            ['name' => 'LDH', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 1000],
            ['name' => 'Urinary Amylasc', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 60, 'price' => 1000],
            ['name' => 'S.Pro-Calcitonin', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 70, 'price' => 2000],
            ['name' => 'CCR', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 1000],
            ['name' => 's. Laipasc', 'category_id' => 2, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 2000],
//            CATEGORY ONE (3)
            ['name' => 'Electrolytes(Government Price)', 'category_id' => 3, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 1000],
            ['name' => 'Sodium(Na+)', 'category_id' => 3, 'branch_id' => 2, 'reefer_fee' => 50, 'price' => 350],
            ['name' => 'Potassium(K+)', 'category_id' => 3, 'branch_id' => 2, 'reefer_fee' => 40, 'price' => 350],
            ['name' => 'Chloride(CL+)', 'category_id' => 3, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 350],
//            Category (4)

            ['name' => 'Blood Grouping', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 200],
            ['name' => 'ASO Titre(Qualitative)', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 600],
            ['name' => 'ASO Titre(Quantitative)', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 1000],
            ['name' => 'RA/RF(Qualitative)', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 600],
            ['name' => 'RA/RF(Quantitative)', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 1000],
            ['name' => 'Febrile Antigen/Triple Antigen', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 1200],
            ['name' => 'Widal Test', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 500],
            ['name' => 'CRP(Government Price)', 'price' => 600, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'CRP(Quantitative)', 'price' => 1000, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Hexagon TB', 'price' => 1200, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'MT', 'price' => 400, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'VDRL', 'price' => 400, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'TPHA', 'price' => 600, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Semen Analysis', 'price' => 700, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Skin Scraping', 'price' => 500, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Nail Cutting Dermatophytes Scraping', 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30, 'price' => 500],
            ['name' => 'Aldehyde Test ', 'price' => 800, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Rh Antibody Titre', 'price' => 800, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'CFT For Filaria', 'price' => 1200, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'ICT For Filaria', 'price' => 1000, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'ICT For Malaria', 'price' => 1000, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'CFT For Kala – Azar ', 'price' => 1000, 'category_id' => 4, 'branch_id' => 2, 'reefer_fee' => 30],
//            Category (5)
            ['name' => 'Urine R/E & M/E', 'price' => 300, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Pregnancy Test/HCG ', 'price' => 300, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Specific Gravity ', 'price' => 200, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Albumin', 'price' => 200, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Urine Sugar', 'price' => 200, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Keton Body ', 'price' => 300, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'ACR', 'price' => 800, 'category_id' => 5, 'branch_id' => 2, 'reefer_fee' => 30],
//            CATEGORY ONE (6)
            ['name' => 'Stool: R/E & M/E', 'price' => 300, 'category_id' => 6, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Stool OBT ', 'price' => 300, 'category_id' => 6, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => 'Stool R/S ', 'price' => 300, 'category_id' => 6, 'branch_id' => 2, 'reefer_fee' => 30],
//            CATEGORY ONE (7)
            ['name' => "Pus For Gram's Stain", 'price' => 600, 'category_id' => 7, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Throat Swab Gram's Stain", 'price' => 600, 'category_id' => 7, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Sputum Gram's Stain", 'price' => 600, 'category_id' => 7, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Sputum For AFB", 'price' => 500, 'category_id' => 7, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Prostatic Gram's Stain ", 'price' => 600, 'category_id' => 7, 'branch_id' => 2, 'reefer_fee' => 30],
//            CATEGORY ONE (8)
            ['name' => "T3,T4,TSH", 'price' => 3300, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "T3", 'price' => 1100, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "T4", 'price' => 1100, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "TSH", 'price' => 1100, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "FT3", 'price' => 1200, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "FT4", 'price' => 1200, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Ferritin (Government Price)", 'price' => 1200, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Prolactin ", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "FSH", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "LH ", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "BNP", 'price' => 3000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Testosterone", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Total IgE (Quantitative)", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "IgE-ICT", 'price' => 800, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dengue IgG/IgM (Government Price) ", 'price' => 300, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dengue NS1 (Government Price)", 'price' => 300, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Troponin-1", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "H pylori (Quantitative) ", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "H pylori ICT ", 'price' => 800, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HbAlc", 'price' => 1300, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "CA-125", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "CA-15.3", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "ANA/ANF ", 'price' => 1200, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Anti DS DNA", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Alpha fetoprotein (AFP)", 'price' => 2000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Vitamin-D", 'price' => 4600, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Torch", 'price' => 10000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Estradiol", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "PSA", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Estrogen", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Progestertone ", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HIV ICT", 'price' => 1000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Hcv ICT", 'price' => 1000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HBe Elisa", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HBeAg ICT", 'price' => 1000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HBeAg Elisa", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HBsAg (Screening) ICT", 'price' => 500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "HBsAg Elisa", 'price' => 1200, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dope Test (Multi Drug)", 'price' => 4000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Cross Matching With Scanning Test ", 'price' => 1000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "AMH ", 'price' => 4500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "B-HCG", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Anti-CCP-AR", 'price' => 2000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Anti Hbs Total", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Anti CCP-AB ", 'price' => 2000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "EGfr", 'price' => 1500, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Vitamin B-12 ", 'price' => 2200, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "S. Coirtisol ", 'price' => 3000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "S. Iron", 'price' => 1000, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "TIBC", 'price' => 2800, 'category_id' => 8, 'branch_id' => 2, 'reefer_fee' => 30],
            //            CATEGORY ONE (9)
            ['name' => "Blood C/S", 'price' => 1300, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Urine C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Stool C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Pus C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Throat Swab C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Eye Swab C/S", 'price' => 800, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Vasinal Swab C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Wound Swab C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Sputurn C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Nasal Swab C/S", 'price' => 1050, 'category_id' => 9, 'branch_id' => 2, 'reefer_fee' => 30],
            //            CATEGORY ONE (10)
            ['name' => "Orthopantomogram (OPG) ", 'price' => 700, 'category_id' => 10, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dental X-Ray", 'price' => 300, 'category_id' => 10, 'branch_id' => 2, 'reefer_fee' => 30],
            //            CATEGORY ONE (11)
            ['name' => "Chest P\A View (Government Price) ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Chest Both View ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Chest AP View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Chest AP Lat. View ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Chest Lat. View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Chest AP Lat. Both Oblique ", 'price' =>2000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Chest PA Lat. Both Oblique ", 'price' =>2000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "P.N.S (OM) View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "P.N.S Both View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Nasal Bon Lat. View. ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Nasal Bon Both. View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Mastoid Townes View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Mandible Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "IM Joint Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "TM Joint Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Both TM Joint Both View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Skull A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Skull Both View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Skull Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Orbit P/A View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Orbit Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Cervical Spine A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Cervical Spine Both View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Cervical Spine A/P Lat Both Oblique ", 'price' =>1600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Soft Tissue Neck A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Soft Tissue Neck Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Neck Both View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Neck A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Neck Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Shoulder Joint Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Scapula Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Both Scapula AP View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Both Scapula AP Lat View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Clavicle AP View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Nasopharynx Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Arm Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Elbow Joint Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Elbow Joint A/P Lat Both Oblique View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Wrist Joint Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Wrist Joint A/P Lat Both Oblique View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Both Wrist Joint A/P Lat Both Oblique View ", 'price' =>2000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Hand Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Hand A/P Lat Both Oblique View ", 'price' =>1000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Finger Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Fore Arm Both View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Fore Arm A/P Lat Both Oblique View ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dorsal Spine Both View ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dorsal Lumbar Spine Both View ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dorsal Lumbar A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dorsal Lumbar A/P Lat Both Oblique View ", 'price' =>2000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Dorsal Lumber Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Thoracic Spine Both View ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Thoracic Spine A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Thoracic Spine Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Lumbar Thoracic Spine Both view ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "-Lumbar Sacral Spine Both view ", 'price' =>1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Lumbar Sacral A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Lumber Sacral Lat View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Lumbar Sacral Spine A/P Lat Both Oblique View ", 'price' =>2000, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Plain Abdomen A/P View ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Plain Abdomen P/A View", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Plain KUB ", 'price' =>600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Pelvis AP View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Pelvis Both View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Pelvis Inlet View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Pelvis Outlet View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Lt Hip Joint Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Rt Hip Joint Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Femur Both view ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Thigh Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Knee Joint Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Both Knee Joint Both View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Knee A/P Lat Both Oblique View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Knee Skyline View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Leg Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Leg A/P Lat Oblique View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Tibia-Fibula Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Ankle Joint Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Ankle Mortise View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Ankle A/P Lat Oblique View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Head Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Foot Both View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Foot A/P Lat both Oblique View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Both Foot Both View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Sacrum Both View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Sacrum Coccyx Both View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "SI Joint Both View ", 'price' => 1100, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Rt.SI Joint AP View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Lt SI Joint AP View ", 'price' => 600, 'category_id' => 11, 'branch_id' => 2, 'reefer_fee' => 30],
            //            CATEGORY ONE (12)

            ['name' => "Barium Swallow/Esophagus ", 'price' => 1700, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Barium Meal S/D ", 'price' => 1700, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Barium Meal Follow Through ", 'price' => 3000, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Barium Follow Through ", 'price' => 2500, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "Barium Enema ", 'price' => 2500, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "RGU & MCU ", 'price' => 2600, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "IVU Without Contrast ", 'price' => 3000, 'category_id' => 12, 'branch_id' => 2, 'reefer_fee' => 30],
            //            CATEGORY ONE (13)
            ['name' => "USG of Hepatobiliary System(HBS) ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Whole Abdomen ", 'price' => 1200, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Upper Abdomen ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Lower Abdomen ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of KUB ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of KUB & PVR ", 'price' => 1200, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of KUB & Prostate ", 'price' => 1200, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of KUB & Prostate with PVR ", 'price' => 1200, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of KUB & Prostate MCC PVR ", 'price' => 1300, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Breast ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Thyroid ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Pregnancy ", 'price' => 1000, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Pregnancy Profile With Fetal H/R WIT AFT ", 'price' => 1200, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Testis ", 'price' => 1200, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            ['name' => "USG of Both Breast ", 'price' => 1800, 'category_id' => 13, 'branch_id' => 2, 'reefer_fee' => 30],
            //            CATEGORY ONE (14)
            ['name' => "ECG ", 'price' => 400, 'category_id' => 14, 'branch_id' => 2,'reefer_fee' => 30],
            ['name' => "Echocardiogram (2D & Mode) ", 'price' => 1400, 'category_id' => 14, 'branch_id' => 2,'reefer_fee' => 30],
            ['name' => "Color Doppler Echo (C/D) ", 'price' => 3000, 'category_id' => 14, 'branch_id' => 2,'reefer_fee' => 30],

            //            CATEGORY ONE (15)
            ['name' => "Video Endoscopy ", 'price' => 2500, 'category_id' => 15, 'branch_id' => 2,'reefer_fee' => 30],
        ];
// Starting code number
        $codeStart = 101;

// Add a code to each product
        foreach ($products as &$product) {
            $product['code'] = $codeStart++;
        }
        \DB::table('products')->insert($products);
    }
}




